# Generated by Django 3.2.2 on 2021-06-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default='dojo antiguo'),
            preserve_default=False,
        ),
    ]
